package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CActividad generated by hbm2java
 */
@Entity
@Table(name = "C_Actividad", catalog = "PGF")
public class CActividad implements java.io.Serializable {

	private int idCActividad;
	private String nombre;

	public CActividad() {
	}

	public CActividad(int idCActividad, String nombre) {
		this.idCActividad = idCActividad;
		this.nombre = nombre;
	}

	@Id

	@Column(name = "idC_Actividad", unique = true, nullable = false)
	public int getIdCActividad() {
		return this.idCActividad;
	}

	public void setIdCActividad(int idCActividad) {
		this.idCActividad = idCActividad;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
