package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CajaChicaId generated by hbm2java
 */
@Embeddable
public class CajaChicaId implements java.io.Serializable {

	private int idCajaChica;
	private int internosIdInternos;

	public CajaChicaId() {
	}

	public CajaChicaId(int idCajaChica, int internosIdInternos) {
		this.idCajaChica = idCajaChica;
		this.internosIdInternos = internosIdInternos;
	}

	@Column(name = "idCaja_Chica", nullable = false)
	public int getIdCajaChica() {
		return this.idCajaChica;
	}

	public void setIdCajaChica(int idCajaChica) {
		this.idCajaChica = idCajaChica;
	}

	@Column(name = "Internos_idInternos", nullable = false)
	public int getInternosIdInternos() {
		return this.internosIdInternos;
	}

	public void setInternosIdInternos(int internosIdInternos) {
		this.internosIdInternos = internosIdInternos;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CajaChicaId))
			return false;
		CajaChicaId castOther = (CajaChicaId) other;

		return (this.getIdCajaChica() == castOther.getIdCajaChica())
				&& (this.getInternosIdInternos() == castOther.getInternosIdInternos());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCajaChica();
		result = 37 * result + this.getInternosIdInternos();
		return result;
	}

}
