package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CalificacionId generated by hbm2java
 */
@Embeddable
public class CalificacionId implements java.io.Serializable {

	private int idDeUsuario;
	private int idAusuario;
	private int idRubro;
	private int idObra;

	public CalificacionId() {
	}

	public CalificacionId(int idDeUsuario, int idAusuario, int idRubro, int idObra) {
		this.idDeUsuario = idDeUsuario;
		this.idAusuario = idAusuario;
		this.idRubro = idRubro;
		this.idObra = idObra;
	}

	@Column(name = "idDeUsuario", nullable = false)
	public int getIdDeUsuario() {
		return this.idDeUsuario;
	}

	public void setIdDeUsuario(int idDeUsuario) {
		this.idDeUsuario = idDeUsuario;
	}

	@Column(name = "idAUsuario", nullable = false)
	public int getIdAusuario() {
		return this.idAusuario;
	}

	public void setIdAusuario(int idAusuario) {
		this.idAusuario = idAusuario;
	}

	@Column(name = "idRubro", nullable = false)
	public int getIdRubro() {
		return this.idRubro;
	}

	public void setIdRubro(int idRubro) {
		this.idRubro = idRubro;
	}

	@Column(name = "idObra", nullable = false)
	public int getIdObra() {
		return this.idObra;
	}

	public void setIdObra(int idObra) {
		this.idObra = idObra;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CalificacionId))
			return false;
		CalificacionId castOther = (CalificacionId) other;

		return (this.getIdDeUsuario() == castOther.getIdDeUsuario())
				&& (this.getIdAusuario() == castOther.getIdAusuario()) && (this.getIdRubro() == castOther.getIdRubro())
				&& (this.getIdObra() == castOther.getIdObra());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdDeUsuario();
		result = 37 * result + this.getIdAusuario();
		result = 37 * result + this.getIdRubro();
		result = 37 * result + this.getIdObra();
		return result;
	}

}
