package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CItemCaja generated by hbm2java
 */
@Entity
@Table(name = "C_Item_Caja", catalog = "PGF")
public class CItemCaja implements java.io.Serializable {

	private int idCItemCaja;
	private String nombre;

	public CItemCaja() {
	}

	public CItemCaja(int idCItemCaja, String nombre) {
		this.idCItemCaja = idCItemCaja;
		this.nombre = nombre;
	}

	@Id

	@Column(name = "idC_Item_Caja", unique = true, nullable = false)
	public int getIdCItemCaja() {
		return this.idCItemCaja;
	}

	public void setIdCItemCaja(int idCItemCaja) {
		this.idCItemCaja = idCItemCaja;
	}

	@Column(name = "Nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
