package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "Cliente", catalog = "PGF")
public class Cliente implements java.io.Serializable {

	private Integer idCliente;
	private int idUsuario;
	private String clase;
	private String subcliente;

	public Cliente() {
	}

	public Cliente(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Cliente(int idUsuario, String clase, String subcliente) {
		this.idUsuario = idUsuario;
		this.clase = clase;
		this.subcliente = subcliente;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCliente", unique = true, nullable = false)
	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	@Column(name = "idUsuario", nullable = false)
	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "Clase", length = 45)
	public String getClase() {
		return this.clase;
	}

	public void setClase(String clase) {
		this.clase = clase;
	}

	@Column(name = "Subcliente", length = 45)
	public String getSubcliente() {
		return this.subcliente;
	}

	public void setSubcliente(String subcliente) {
		this.subcliente = subcliente;
	}

}
