package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Contratista generated by hbm2java
 */
@Entity
@Table(name = "Contratista", catalog = "PGF")
public class Contratista implements java.io.Serializable {

	private Integer idContratista;
	private int idUsuario;

	public Contratista() {
	}

	public Contratista(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idContratista", unique = true, nullable = false)
	public Integer getIdContratista() {
		return this.idContratista;
	}

	public void setIdContratista(Integer idContratista) {
		this.idContratista = idContratista;
	}

	@Column(name = "idUsuario", nullable = false)
	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

}
