package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CRolObra generated by hbm2java
 */
@Entity
@Table(name = "C_Rol_Obra", catalog = "PGF")
public class CRolObra implements java.io.Serializable {

	private int idCRolObra;
	private String rol;

	public CRolObra() {
	}

	public CRolObra(int idCRolObra, String rol) {
		this.idCRolObra = idCRolObra;
		this.rol = rol;
	}

	@Id

	@Column(name = "idC_Rol_Obra", unique = true, nullable = false)
	public int getIdCRolObra() {
		return this.idCRolObra;
	}

	public void setIdCRolObra(int idCRolObra) {
		this.idCRolObra = idCRolObra;
	}

	@Column(name = "Rol", nullable = false, length = 10)
	public String getRol() {
		return this.rol;
	}

	public void setRol(String rol) {
		this.rol = rol;
	}

}
