package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CRolUsuario generated by hbm2java
 */
@Entity
@Table(name = "C_Rol_Usuario", catalog = "PGF")
public class CRolUsuario implements java.io.Serializable {

	private Integer idCRolUsuario;
	private String nombre;

	public CRolUsuario() {
	}

	public CRolUsuario(String nombre) {
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idC_Rol_Usuario", unique = true, nullable = false)
	public Integer getIdCRolUsuario() {
		return this.idCRolUsuario;
	}

	public void setIdCRolUsuario(Integer idCRolUsuario) {
		this.idCRolUsuario = idCRolUsuario;
	}

	@Column(name = "Nombre", nullable = false, length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
