package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CRubros generated by hbm2java
 */
@Entity
@Table(name = "C_Rubros", catalog = "PGF")
public class CRubros implements java.io.Serializable {

	private Integer idCRubros;
	private String nombre;

	public CRubros() {
	}

	public CRubros(String nombre) {
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idC_Rubros", unique = true, nullable = false)
	public Integer getIdCRubros() {
		return this.idCRubros;
	}

	public void setIdCRubros(Integer idCRubros) {
		this.idCRubros = idCRubros;
	}

	@Column(name = "Nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
