package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CStastusSolicitudPago generated by hbm2java
 */
@Entity
@Table(name = "C_Stastus_Solicitud_Pago", catalog = "PGF")
public class CStastusSolicitudPago implements java.io.Serializable {

	private Integer idCStastusSolicitudPago;
	private String nombre;

	public CStastusSolicitudPago() {
	}

	public CStastusSolicitudPago(String nombre) {
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idC_Stastus_Solicitud_Pago", unique = true, nullable = false)
	public Integer getIdCStastusSolicitudPago() {
		return this.idCStastusSolicitudPago;
	}

	public void setIdCStastusSolicitudPago(Integer idCStastusSolicitudPago) {
		this.idCStastusSolicitudPago = idCStastusSolicitudPago;
	}

	@Column(name = "Nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
