package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CTipoPresupuesto generated by hbm2java
 */
@Entity
@Table(name = "C_Tipo_Presupuesto", catalog = "PGF")
public class CTipoPresupuesto implements java.io.Serializable {

	private int idCTipoPresupuesto;
	private String nombre;

	public CTipoPresupuesto() {
	}

	public CTipoPresupuesto(int idCTipoPresupuesto) {
		this.idCTipoPresupuesto = idCTipoPresupuesto;
	}

	public CTipoPresupuesto(int idCTipoPresupuesto, String nombre) {
		this.idCTipoPresupuesto = idCTipoPresupuesto;
		this.nombre = nombre;
	}

	@Id

	@Column(name = "idC_Tipo_Presupuesto", unique = true, nullable = false)
	public int getIdCTipoPresupuesto() {
		return this.idCTipoPresupuesto;
	}

	public void setIdCTipoPresupuesto(int idCTipoPresupuesto) {
		this.idCTipoPresupuesto = idCTipoPresupuesto;
	}

	@Column(name = "Nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
