package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CTipoPago generated by hbm2java
 */
@Entity
@Table(name = "C_Tipo_Pago", catalog = "PGF")
public class CTipoPago implements java.io.Serializable {

	private int idCTipoPago;
	private String tipoPago;

	public CTipoPago() {
	}

	public CTipoPago(int idCTipoPago) {
		this.idCTipoPago = idCTipoPago;
	}

	public CTipoPago(int idCTipoPago, String tipoPago) {
		this.idCTipoPago = idCTipoPago;
		this.tipoPago = tipoPago;
	}

	@Id

	@Column(name = "idC_Tipo_Pago", unique = true, nullable = false)
	public int getIdCTipoPago() {
		return this.idCTipoPago;
	}

	public void setIdCTipoPago(int idCTipoPago) {
		this.idCTipoPago = idCTipoPago;
	}

	@Column(name = "Tipo_pago", length = 45)
	public String getTipoPago() {
		return this.tipoPago;
	}

	public void setTipoPago(String tipoPago) {
		this.tipoPago = tipoPago;
	}

}
