package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CTipoDireccion generated by hbm2java
 */
@Entity
@Table(name = "C_Tipo_Direccion", catalog = "PGF")
public class CTipoDireccion implements java.io.Serializable {

	private int idCTipoDireccion;
	private String tipoDireccion;

	public CTipoDireccion() {
	}

	public CTipoDireccion(int idCTipoDireccion) {
		this.idCTipoDireccion = idCTipoDireccion;
	}

	public CTipoDireccion(int idCTipoDireccion, String tipoDireccion) {
		this.idCTipoDireccion = idCTipoDireccion;
		this.tipoDireccion = tipoDireccion;
	}

	@Id

	@Column(name = "idC_Tipo_Direccion", unique = true, nullable = false)
	public int getIdCTipoDireccion() {
		return this.idCTipoDireccion;
	}

	public void setIdCTipoDireccion(int idCTipoDireccion) {
		this.idCTipoDireccion = idCTipoDireccion;
	}

	@Column(name = "Tipo_Direccion", length = 45)
	public String getTipoDireccion() {
		return this.tipoDireccion;
	}

	public void setTipoDireccion(String tipoDireccion) {
		this.tipoDireccion = tipoDireccion;
	}

}
