package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CTipoComprobante generated by hbm2java
 */
@Entity
@Table(name = "C_Tipo_Comprobante", catalog = "PGF")
public class CTipoComprobante implements java.io.Serializable {

	private int idCTipoComprobante;
	private String nombre;

	public CTipoComprobante() {
	}

	public CTipoComprobante(int idCTipoComprobante) {
		this.idCTipoComprobante = idCTipoComprobante;
	}

	public CTipoComprobante(int idCTipoComprobante, String nombre) {
		this.idCTipoComprobante = idCTipoComprobante;
		this.nombre = nombre;
	}

	@Id

	@Column(name = "idC_Tipo_Comprobante", unique = true, nullable = false)
	public int getIdCTipoComprobante() {
		return this.idCTipoComprobante;
	}

	public void setIdCTipoComprobante(int idCTipoComprobante) {
		this.idCTipoComprobante = idCTipoComprobante;
	}

	@Column(name = "Nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
