package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CuentaBancaria generated by hbm2java
 */
@Entity
@Table(name = "Cuenta_Bancaria", catalog = "PGF")
public class CuentaBancaria implements java.io.Serializable {

	private CuentaBancariaId id;
	private String numeroCuenta;
	private String clabeInterbancaria;
	private String sucursal;
	private String titular;

	public CuentaBancaria() {
	}

	public CuentaBancaria(CuentaBancariaId id, String titular) {
		this.id = id;
		this.titular = titular;
	}

	public CuentaBancaria(CuentaBancariaId id, String numeroCuenta, String clabeInterbancaria, String sucursal,
			String titular) {
		this.id = id;
		this.numeroCuenta = numeroCuenta;
		this.clabeInterbancaria = clabeInterbancaria;
		this.sucursal = sucursal;
		this.titular = titular;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idCuentaBancaria", column = @Column(name = "idCuenta_Bancaria", nullable = false) ),
			@AttributeOverride(name = "bancoIdBanco", column = @Column(name = "Banco_idBanco", nullable = false) ),
			@AttributeOverride(name = "direccionIdDireccion", column = @Column(name = "Direccion_idDireccion", nullable = false) ) })
	public CuentaBancariaId getId() {
		return this.id;
	}

	public void setId(CuentaBancariaId id) {
		this.id = id;
	}

	@Column(name = "Numero_Cuenta", length = 45)
	public String getNumeroCuenta() {
		return this.numeroCuenta;
	}

	public void setNumeroCuenta(String numeroCuenta) {
		this.numeroCuenta = numeroCuenta;
	}

	@Column(name = "Clabe_Interbancaria", length = 45)
	public String getClabeInterbancaria() {
		return this.clabeInterbancaria;
	}

	public void setClabeInterbancaria(String clabeInterbancaria) {
		this.clabeInterbancaria = clabeInterbancaria;
	}

	@Column(name = "Sucursal", length = 45)
	public String getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(String sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "Titular", nullable = false, length = 45)
	public String getTitular() {
		return this.titular;
	}

	public void setTitular(String titular) {
		this.titular = titular;
	}

}
