package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CuentaBancariaId generated by hbm2java
 */
@Embeddable
public class CuentaBancariaId implements java.io.Serializable {

	private int idCuentaBancaria;
	private int bancoIdBanco;
	private int direccionIdDireccion;

	public CuentaBancariaId() {
	}

	public CuentaBancariaId(int idCuentaBancaria, int bancoIdBanco, int direccionIdDireccion) {
		this.idCuentaBancaria = idCuentaBancaria;
		this.bancoIdBanco = bancoIdBanco;
		this.direccionIdDireccion = direccionIdDireccion;
	}

	@Column(name = "idCuenta_Bancaria", nullable = false)
	public int getIdCuentaBancaria() {
		return this.idCuentaBancaria;
	}

	public void setIdCuentaBancaria(int idCuentaBancaria) {
		this.idCuentaBancaria = idCuentaBancaria;
	}

	@Column(name = "Banco_idBanco", nullable = false)
	public int getBancoIdBanco() {
		return this.bancoIdBanco;
	}

	public void setBancoIdBanco(int bancoIdBanco) {
		this.bancoIdBanco = bancoIdBanco;
	}

	@Column(name = "Direccion_idDireccion", nullable = false)
	public int getDireccionIdDireccion() {
		return this.direccionIdDireccion;
	}

	public void setDireccionIdDireccion(int direccionIdDireccion) {
		this.direccionIdDireccion = direccionIdDireccion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CuentaBancariaId))
			return false;
		CuentaBancariaId castOther = (CuentaBancariaId) other;

		return (this.getIdCuentaBancaria() == castOther.getIdCuentaBancaria())
				&& (this.getBancoIdBanco() == castOther.getBancoIdBanco())
				&& (this.getDireccionIdDireccion() == castOther.getDireccionIdDireccion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCuentaBancaria();
		result = 37 * result + this.getBancoIdBanco();
		result = 37 * result + this.getDireccionIdDireccion();
		return result;
	}

}
