package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Direccion generated by hbm2java
 */
@Entity
@Table(name = "Direccion", catalog = "PGF")
public class Direccion implements java.io.Serializable {

	private Integer idDireccion;
	private String calle;
	private String colonia;
	private String numExt;
	private String numInt;
	private String delegacion;
	private String estado;
	private String cp;
	private String pais;
	private int CTipoDireccionIdCTipoDireccion;

	public Direccion() {
	}

	public Direccion(int CTipoDireccionIdCTipoDireccion) {
		this.CTipoDireccionIdCTipoDireccion = CTipoDireccionIdCTipoDireccion;
	}

	public Direccion(String calle, String colonia, String numExt, String numInt, String delegacion, String estado,
			String cp, String pais, int CTipoDireccionIdCTipoDireccion) {
		this.calle = calle;
		this.colonia = colonia;
		this.numExt = numExt;
		this.numInt = numInt;
		this.delegacion = delegacion;
		this.estado = estado;
		this.cp = cp;
		this.pais = pais;
		this.CTipoDireccionIdCTipoDireccion = CTipoDireccionIdCTipoDireccion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idDireccion", unique = true, nullable = false)
	public Integer getIdDireccion() {
		return this.idDireccion;
	}

	public void setIdDireccion(Integer idDireccion) {
		this.idDireccion = idDireccion;
	}

	@Column(name = "Calle", length = 45)
	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	@Column(name = "Colonia", length = 45)
	public String getColonia() {
		return this.colonia;
	}

	public void setColonia(String colonia) {
		this.colonia = colonia;
	}

	@Column(name = "NumExt", length = 45)
	public String getNumExt() {
		return this.numExt;
	}

	public void setNumExt(String numExt) {
		this.numExt = numExt;
	}

	@Column(name = "NumInt", length = 45)
	public String getNumInt() {
		return this.numInt;
	}

	public void setNumInt(String numInt) {
		this.numInt = numInt;
	}

	@Column(name = "Delegacion", length = 45)
	public String getDelegacion() {
		return this.delegacion;
	}

	public void setDelegacion(String delegacion) {
		this.delegacion = delegacion;
	}

	@Column(name = "Estado", length = 45)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "CP", length = 5)
	public String getCp() {
		return this.cp;
	}

	public void setCp(String cp) {
		this.cp = cp;
	}

	@Column(name = "Pais", length = 45)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@Column(name = "C_Tipo_Direccion_idC_Tipo_Direccion", nullable = false)
	public int getCTipoDireccionIdCTipoDireccion() {
		return this.CTipoDireccionIdCTipoDireccion;
	}

	public void setCTipoDireccionIdCTipoDireccion(int CTipoDireccionIdCTipoDireccion) {
		this.CTipoDireccionIdCTipoDireccion = CTipoDireccionIdCTipoDireccion;
	}

}
