package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Interno generated by hbm2java
 */
@Entity
@Table(name = "Interno", catalog = "PGF")
public class Interno implements java.io.Serializable {

	private Integer idInternos;
	private int idUsuario;

	public Interno() {
	}

	public Interno(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idInternos", unique = true, nullable = false)
	public Integer getIdInternos() {
		return this.idInternos;
	}

	public void setIdInternos(Integer idInternos) {
		this.idInternos = idInternos;
	}

	@Column(name = "idUsuario", nullable = false)
	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

}
