package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ItemAutorizadosId generated by hbm2java
 */
@Embeddable
public class ItemAutorizadosId implements java.io.Serializable {

	private int idItemAutorizados;
	private int CItemCajaIdCItemCaja;
	private int CTipoComprobanteIdCTipoComprobante;
	private int cajaChicaIdCajaChica;
	private int cajaChicaInternosIdInternos;

	public ItemAutorizadosId() {
	}

	public ItemAutorizadosId(int idItemAutorizados, int CItemCajaIdCItemCaja, int CTipoComprobanteIdCTipoComprobante,
			int cajaChicaIdCajaChica, int cajaChicaInternosIdInternos) {
		this.idItemAutorizados = idItemAutorizados;
		this.CItemCajaIdCItemCaja = CItemCajaIdCItemCaja;
		this.CTipoComprobanteIdCTipoComprobante = CTipoComprobanteIdCTipoComprobante;
		this.cajaChicaIdCajaChica = cajaChicaIdCajaChica;
		this.cajaChicaInternosIdInternos = cajaChicaInternosIdInternos;
	}

	@Column(name = "idItem_Autorizados", nullable = false)
	public int getIdItemAutorizados() {
		return this.idItemAutorizados;
	}

	public void setIdItemAutorizados(int idItemAutorizados) {
		this.idItemAutorizados = idItemAutorizados;
	}

	@Column(name = "C_Item_Caja_idC_Item_Caja", nullable = false)
	public int getCItemCajaIdCItemCaja() {
		return this.CItemCajaIdCItemCaja;
	}

	public void setCItemCajaIdCItemCaja(int CItemCajaIdCItemCaja) {
		this.CItemCajaIdCItemCaja = CItemCajaIdCItemCaja;
	}

	@Column(name = "C_Tipo_Comprobante_idC_Tipo_Comprobante", nullable = false)
	public int getCTipoComprobanteIdCTipoComprobante() {
		return this.CTipoComprobanteIdCTipoComprobante;
	}

	public void setCTipoComprobanteIdCTipoComprobante(int CTipoComprobanteIdCTipoComprobante) {
		this.CTipoComprobanteIdCTipoComprobante = CTipoComprobanteIdCTipoComprobante;
	}

	@Column(name = "Caja_Chica_idCaja_Chica", nullable = false)
	public int getCajaChicaIdCajaChica() {
		return this.cajaChicaIdCajaChica;
	}

	public void setCajaChicaIdCajaChica(int cajaChicaIdCajaChica) {
		this.cajaChicaIdCajaChica = cajaChicaIdCajaChica;
	}

	@Column(name = "Caja_Chica_Internos_idInternos", nullable = false)
	public int getCajaChicaInternosIdInternos() {
		return this.cajaChicaInternosIdInternos;
	}

	public void setCajaChicaInternosIdInternos(int cajaChicaInternosIdInternos) {
		this.cajaChicaInternosIdInternos = cajaChicaInternosIdInternos;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ItemAutorizadosId))
			return false;
		ItemAutorizadosId castOther = (ItemAutorizadosId) other;

		return (this.getIdItemAutorizados() == castOther.getIdItemAutorizados())
				&& (this.getCItemCajaIdCItemCaja() == castOther.getCItemCajaIdCItemCaja())
				&& (this.getCTipoComprobanteIdCTipoComprobante() == castOther.getCTipoComprobanteIdCTipoComprobante())
				&& (this.getCajaChicaIdCajaChica() == castOther.getCajaChicaIdCajaChica())
				&& (this.getCajaChicaInternosIdInternos() == castOther.getCajaChicaInternosIdInternos());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdItemAutorizados();
		result = 37 * result + this.getCItemCajaIdCItemCaja();
		result = 37 * result + this.getCTipoComprobanteIdCTipoComprobante();
		result = 37 * result + this.getCajaChicaIdCajaChica();
		result = 37 * result + this.getCajaChicaInternosIdInternos();
		return result;
	}

}
