package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ItemsPresupuesto generated by hbm2java
 */
@Entity
@Table(name = "Items_Presupuesto", catalog = "PGF")
public class ItemsPresupuesto implements java.io.Serializable {

	private int idItemsPresupuesto;
	private int presupuestoIdPresupuesto;
	private String clave;
	private String nombre;
	private Integer cantidad;
	private String unidad;
	private Byte precioUnitario;
	private String precioUnitarioLetra;

	public ItemsPresupuesto() {
	}

	public ItemsPresupuesto(int idItemsPresupuesto, int presupuestoIdPresupuesto) {
		this.idItemsPresupuesto = idItemsPresupuesto;
		this.presupuestoIdPresupuesto = presupuestoIdPresupuesto;
	}

	public ItemsPresupuesto(int idItemsPresupuesto, int presupuestoIdPresupuesto, String clave, String nombre,
			Integer cantidad, String unidad, Byte precioUnitario, String precioUnitarioLetra) {
		this.idItemsPresupuesto = idItemsPresupuesto;
		this.presupuestoIdPresupuesto = presupuestoIdPresupuesto;
		this.clave = clave;
		this.nombre = nombre;
		this.cantidad = cantidad;
		this.unidad = unidad;
		this.precioUnitario = precioUnitario;
		this.precioUnitarioLetra = precioUnitarioLetra;
	}

	@Id

	@Column(name = "idItems_Presupuesto", unique = true, nullable = false)
	public int getIdItemsPresupuesto() {
		return this.idItemsPresupuesto;
	}

	public void setIdItemsPresupuesto(int idItemsPresupuesto) {
		this.idItemsPresupuesto = idItemsPresupuesto;
	}

	@Column(name = "Presupuesto_idPresupuesto", nullable = false)
	public int getPresupuestoIdPresupuesto() {
		return this.presupuestoIdPresupuesto;
	}

	public void setPresupuestoIdPresupuesto(int presupuestoIdPresupuesto) {
		this.presupuestoIdPresupuesto = presupuestoIdPresupuesto;
	}

	@Column(name = "Clave", length = 45)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "Nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Cantidad")
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "Unidad", length = 45)
	public String getUnidad() {
		return this.unidad;
	}

	public void setUnidad(String unidad) {
		this.unidad = unidad;
	}

	@Column(name = "Precio_Unitario", precision = 2, scale = 0)
	public Byte getPrecioUnitario() {
		return this.precioUnitario;
	}

	public void setPrecioUnitario(Byte precioUnitario) {
		this.precioUnitario = precioUnitario;
	}

	@Column(name = "Precio_Unitario_Letra", length = 45)
	public String getPrecioUnitarioLetra() {
		return this.precioUnitarioLetra;
	}

	public void setPrecioUnitarioLetra(String precioUnitarioLetra) {
		this.precioUnitarioLetra = precioUnitarioLetra;
	}

}
