package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ItemRegistrado generated by hbm2java
 */
@Entity
@Table(name = "Item_Registrado", catalog = "PGF")
public class ItemRegistrado implements java.io.Serializable {

	private ItemRegistradoId id;
	private byte importe;
	private Date fecha;
	private int obraIdObra;

	public ItemRegistrado() {
	}

	public ItemRegistrado(ItemRegistradoId id, byte importe, Date fecha, int obraIdObra) {
		this.id = id;
		this.importe = importe;
		this.fecha = fecha;
		this.obraIdObra = obraIdObra;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idItemRegistrado", column = @Column(name = "idItem_Registrado", nullable = false) ),
			@AttributeOverride(name = "CTipoComprobanteIdCTipoComprobante", column = @Column(name = "C_Tipo_Comprobante_idC_Tipo_Comprobante", nullable = false) ),
			@AttributeOverride(name = "CItemCajaIdCItemCaja", column = @Column(name = "C_Item_Caja_idC_Item_Caja", nullable = false) ),
			@AttributeOverride(name = "cajaChicaIdCajaChica", column = @Column(name = "Caja_Chica_idCaja_Chica", nullable = false) ),
			@AttributeOverride(name = "cajaChicaInternosIdInternos", column = @Column(name = "Caja_Chica_Internos_idInternos", nullable = false) ) })
	public ItemRegistradoId getId() {
		return this.id;
	}

	public void setId(ItemRegistradoId id) {
		this.id = id;
	}

	@Column(name = "Importe", nullable = false, precision = 2, scale = 0)
	public byte getImporte() {
		return this.importe;
	}

	public void setImporte(byte importe) {
		this.importe = importe;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha", nullable = false, length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "Obra_idObra", nullable = false)
	public int getObraIdObra() {
		return this.obraIdObra;
	}

	public void setObraIdObra(int obraIdObra) {
		this.obraIdObra = obraIdObra;
	}

}
