package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ItemAutorizados generated by hbm2java
 */
@Entity
@Table(name = "Item_Autorizados", catalog = "PGF")
public class ItemAutorizados implements java.io.Serializable {

	private ItemAutorizadosId id;
	private Byte montoPreAutorizado;
	private Byte gastoReal;
	private Byte montoAutorizado;

	public ItemAutorizados() {
	}

	public ItemAutorizados(ItemAutorizadosId id) {
		this.id = id;
	}

	public ItemAutorizados(ItemAutorizadosId id, Byte montoPreAutorizado, Byte gastoReal, Byte montoAutorizado) {
		this.id = id;
		this.montoPreAutorizado = montoPreAutorizado;
		this.gastoReal = gastoReal;
		this.montoAutorizado = montoAutorizado;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idItemAutorizados", column = @Column(name = "idItem_Autorizados", nullable = false) ),
			@AttributeOverride(name = "CItemCajaIdCItemCaja", column = @Column(name = "C_Item_Caja_idC_Item_Caja", nullable = false) ),
			@AttributeOverride(name = "CTipoComprobanteIdCTipoComprobante", column = @Column(name = "C_Tipo_Comprobante_idC_Tipo_Comprobante", nullable = false) ),
			@AttributeOverride(name = "cajaChicaIdCajaChica", column = @Column(name = "Caja_Chica_idCaja_Chica", nullable = false) ),
			@AttributeOverride(name = "cajaChicaInternosIdInternos", column = @Column(name = "Caja_Chica_Internos_idInternos", nullable = false) ) })
	public ItemAutorizadosId getId() {
		return this.id;
	}

	public void setId(ItemAutorizadosId id) {
		this.id = id;
	}

	@Column(name = "Monto_PreAutorizado", precision = 2, scale = 0)
	public Byte getMontoPreAutorizado() {
		return this.montoPreAutorizado;
	}

	public void setMontoPreAutorizado(Byte montoPreAutorizado) {
		this.montoPreAutorizado = montoPreAutorizado;
	}

	@Column(name = "Gasto_Real", precision = 2, scale = 0)
	public Byte getGastoReal() {
		return this.gastoReal;
	}

	public void setGastoReal(Byte gastoReal) {
		this.gastoReal = gastoReal;
	}

	@Column(name = "Monto_Autorizado", precision = 2, scale = 0)
	public Byte getMontoAutorizado() {
		return this.montoAutorizado;
	}

	public void setMontoAutorizado(Byte montoAutorizado) {
		this.montoAutorizado = montoAutorizado;
	}

}
