package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Obra generated by hbm2java
 */
@Entity
@Table(name = "Obra", catalog = "PGF")
public class Obra implements java.io.Serializable {

	private int idObra;
	private int clienteIdCliente;
	private String status;
	private String nombre;
	private Integer direccion;
	private Date fechaInicio;
	private Date fechaFin;
	private String tipo;
	private String tiempo;
	private String montoMensual;
	private String porcentaje;
	private String montoTotal;
	private Integer idUnidadNegocio;

	public Obra() {
	}

	public Obra(int idObra, int clienteIdCliente, String nombre) {
		this.idObra = idObra;
		this.clienteIdCliente = clienteIdCliente;
		this.nombre = nombre;
	}

	public Obra(int idObra, int clienteIdCliente, String status, String nombre, Integer direccion, Date fechaInicio,
			Date fechaFin, String tipo, String tiempo, String montoMensual, String porcentaje, String montoTotal,
			Integer idUnidadNegocio) {
		this.idObra = idObra;
		this.clienteIdCliente = clienteIdCliente;
		this.status = status;
		this.nombre = nombre;
		this.direccion = direccion;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.tipo = tipo;
		this.tiempo = tiempo;
		this.montoMensual = montoMensual;
		this.porcentaje = porcentaje;
		this.montoTotal = montoTotal;
		this.idUnidadNegocio = idUnidadNegocio;
	}

	@Id

	@Column(name = "idObra", unique = true, nullable = false)
	public int getIdObra() {
		return this.idObra;
	}

	public void setIdObra(int idObra) {
		this.idObra = idObra;
	}

	@Column(name = "Cliente_idCliente", nullable = false)
	public int getClienteIdCliente() {
		return this.clienteIdCliente;
	}

	public void setClienteIdCliente(int clienteIdCliente) {
		this.clienteIdCliente = clienteIdCliente;
	}

	@Column(name = "Status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "Nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Direccion")
	public Integer getDireccion() {
		return this.direccion;
	}

	public void setDireccion(Integer direccion) {
		this.direccion = direccion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaInicio", length = 19)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaFin", length = 19)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "tipo", length = 45)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "tiempo", length = 45)
	public String getTiempo() {
		return this.tiempo;
	}

	public void setTiempo(String tiempo) {
		this.tiempo = tiempo;
	}

	@Column(name = "montoMensual", length = 45)
	public String getMontoMensual() {
		return this.montoMensual;
	}

	public void setMontoMensual(String montoMensual) {
		this.montoMensual = montoMensual;
	}

	@Column(name = "porcentaje", length = 45)
	public String getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(String porcentaje) {
		this.porcentaje = porcentaje;
	}

	@Column(name = "montoTotal", length = 45)
	public String getMontoTotal() {
		return this.montoTotal;
	}

	public void setMontoTotal(String montoTotal) {
		this.montoTotal = montoTotal;
	}

	@Column(name = "idUnidad_Negocio")
	public Integer getIdUnidadNegocio() {
		return this.idUnidadNegocio;
	}

	public void setIdUnidadNegocio(Integer idUnidadNegocio) {
		this.idUnidadNegocio = idUnidadNegocio;
	}

}
