package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pago generated by hbm2java
 */
@Entity
@Table(name = "Pago", catalog = "PGF")
public class Pago implements java.io.Serializable {

	private PagoId id;
	private Date fechaPago;
	private byte cantidad;
	private String tipoComprobante;
	private int CTipoPagoIdCTipoPago;

	public Pago() {
	}

	public Pago(PagoId id, Date fechaPago, byte cantidad, String tipoComprobante, int CTipoPagoIdCTipoPago) {
		this.id = id;
		this.fechaPago = fechaPago;
		this.cantidad = cantidad;
		this.tipoComprobante = tipoComprobante;
		this.CTipoPagoIdCTipoPago = CTipoPagoIdCTipoPago;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idPago", column = @Column(name = "idPago", nullable = false) ),
			@AttributeOverride(name = "solicitudPagoIdSolicitudPago", column = @Column(name = "Solicitud_Pago_idSolicitud_Pago", nullable = false) ),
			@AttributeOverride(name = "cuentaBancariaIdCuentaBancaria", column = @Column(name = "Cuenta_Bancaria_idCuenta_Bancaria", nullable = false) ),
			@AttributeOverride(name = "cuentaBancariaBancoIdBanco", column = @Column(name = "Cuenta_Bancaria_Banco_idBanco", nullable = false) ),
			@AttributeOverride(name = "cuentaBancariaDireccionIdDireccion", column = @Column(name = "Cuenta_Bancaria_Direccion_idDireccion", nullable = false) ) })
	public PagoId getId() {
		return this.id;
	}

	public void setId(PagoId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Pago", nullable = false, length = 19)
	public Date getFechaPago() {
		return this.fechaPago;
	}

	public void setFechaPago(Date fechaPago) {
		this.fechaPago = fechaPago;
	}

	@Column(name = "Cantidad", nullable = false, precision = 2, scale = 0)
	public byte getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(byte cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "Tipo_Comprobante", nullable = false, length = 45)
	public String getTipoComprobante() {
		return this.tipoComprobante;
	}

	public void setTipoComprobante(String tipoComprobante) {
		this.tipoComprobante = tipoComprobante;
	}

	@Column(name = "C_Tipo_Pago_idC_Tipo_Pago", nullable = false)
	public int getCTipoPagoIdCTipoPago() {
		return this.CTipoPagoIdCTipoPago;
	}

	public void setCTipoPagoIdCTipoPago(int CTipoPagoIdCTipoPago) {
		this.CTipoPagoIdCTipoPago = CTipoPagoIdCTipoPago;
	}

}
