package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PagoId generated by hbm2java
 */
@Embeddable
public class PagoId implements java.io.Serializable {

	private int idPago;
	private int solicitudPagoIdSolicitudPago;
	private int cuentaBancariaIdCuentaBancaria;
	private int cuentaBancariaBancoIdBanco;
	private int cuentaBancariaDireccionIdDireccion;

	public PagoId() {
	}

	public PagoId(int idPago, int solicitudPagoIdSolicitudPago, int cuentaBancariaIdCuentaBancaria,
			int cuentaBancariaBancoIdBanco, int cuentaBancariaDireccionIdDireccion) {
		this.idPago = idPago;
		this.solicitudPagoIdSolicitudPago = solicitudPagoIdSolicitudPago;
		this.cuentaBancariaIdCuentaBancaria = cuentaBancariaIdCuentaBancaria;
		this.cuentaBancariaBancoIdBanco = cuentaBancariaBancoIdBanco;
		this.cuentaBancariaDireccionIdDireccion = cuentaBancariaDireccionIdDireccion;
	}

	@Column(name = "idPago", nullable = false)
	public int getIdPago() {
		return this.idPago;
	}

	public void setIdPago(int idPago) {
		this.idPago = idPago;
	}

	@Column(name = "Solicitud_Pago_idSolicitud_Pago", nullable = false)
	public int getSolicitudPagoIdSolicitudPago() {
		return this.solicitudPagoIdSolicitudPago;
	}

	public void setSolicitudPagoIdSolicitudPago(int solicitudPagoIdSolicitudPago) {
		this.solicitudPagoIdSolicitudPago = solicitudPagoIdSolicitudPago;
	}

	@Column(name = "Cuenta_Bancaria_idCuenta_Bancaria", nullable = false)
	public int getCuentaBancariaIdCuentaBancaria() {
		return this.cuentaBancariaIdCuentaBancaria;
	}

	public void setCuentaBancariaIdCuentaBancaria(int cuentaBancariaIdCuentaBancaria) {
		this.cuentaBancariaIdCuentaBancaria = cuentaBancariaIdCuentaBancaria;
	}

	@Column(name = "Cuenta_Bancaria_Banco_idBanco", nullable = false)
	public int getCuentaBancariaBancoIdBanco() {
		return this.cuentaBancariaBancoIdBanco;
	}

	public void setCuentaBancariaBancoIdBanco(int cuentaBancariaBancoIdBanco) {
		this.cuentaBancariaBancoIdBanco = cuentaBancariaBancoIdBanco;
	}

	@Column(name = "Cuenta_Bancaria_Direccion_idDireccion", nullable = false)
	public int getCuentaBancariaDireccionIdDireccion() {
		return this.cuentaBancariaDireccionIdDireccion;
	}

	public void setCuentaBancariaDireccionIdDireccion(int cuentaBancariaDireccionIdDireccion) {
		this.cuentaBancariaDireccionIdDireccion = cuentaBancariaDireccionIdDireccion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PagoId))
			return false;
		PagoId castOther = (PagoId) other;

		return (this.getIdPago() == castOther.getIdPago())
				&& (this.getSolicitudPagoIdSolicitudPago() == castOther.getSolicitudPagoIdSolicitudPago())
				&& (this.getCuentaBancariaIdCuentaBancaria() == castOther.getCuentaBancariaIdCuentaBancaria())
				&& (this.getCuentaBancariaBancoIdBanco() == castOther.getCuentaBancariaBancoIdBanco())
				&& (this.getCuentaBancariaDireccionIdDireccion() == castOther.getCuentaBancariaDireccionIdDireccion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPago();
		result = 37 * result + this.getSolicitudPagoIdSolicitudPago();
		result = 37 * result + this.getCuentaBancariaIdCuentaBancaria();
		result = 37 * result + this.getCuentaBancariaBancoIdBanco();
		result = 37 * result + this.getCuentaBancariaDireccionIdDireccion();
		return result;
	}

}
