package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PresupuestoStatusChange generated by hbm2java
 */
@Entity
@Table(name = "Presupuesto_Status_Change", catalog = "PGF")
public class PresupuestoStatusChange implements java.io.Serializable {

	private int idPresupuestoStatusChange;
	private int deStatusPresupuesto;
	private int AStatusPresuspuesto;
	private int presupuestoIdPresupuesto;

	public PresupuestoStatusChange() {
	}

	public PresupuestoStatusChange(int idPresupuestoStatusChange, int deStatusPresupuesto, int AStatusPresuspuesto,
			int presupuestoIdPresupuesto) {
		this.idPresupuestoStatusChange = idPresupuestoStatusChange;
		this.deStatusPresupuesto = deStatusPresupuesto;
		this.AStatusPresuspuesto = AStatusPresuspuesto;
		this.presupuestoIdPresupuesto = presupuestoIdPresupuesto;
	}

	@Id

	@Column(name = "idPresupuesto_Status_Change", unique = true, nullable = false)
	public int getIdPresupuestoStatusChange() {
		return this.idPresupuestoStatusChange;
	}

	public void setIdPresupuestoStatusChange(int idPresupuestoStatusChange) {
		this.idPresupuestoStatusChange = idPresupuestoStatusChange;
	}

	@Column(name = "De_Status_Presupuesto", nullable = false)
	public int getDeStatusPresupuesto() {
		return this.deStatusPresupuesto;
	}

	public void setDeStatusPresupuesto(int deStatusPresupuesto) {
		this.deStatusPresupuesto = deStatusPresupuesto;
	}

	@Column(name = "A_Status_Presuspuesto", nullable = false)
	public int getAStatusPresuspuesto() {
		return this.AStatusPresuspuesto;
	}

	public void setAStatusPresuspuesto(int AStatusPresuspuesto) {
		this.AStatusPresuspuesto = AStatusPresuspuesto;
	}

	@Column(name = "Presupuesto_idPresupuesto", nullable = false)
	public int getPresupuestoIdPresupuesto() {
		return this.presupuestoIdPresupuesto;
	}

	public void setPresupuestoIdPresupuesto(int presupuestoIdPresupuesto) {
		this.presupuestoIdPresupuesto = presupuestoIdPresupuesto;
	}

}
