package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * RContratistaObra generated by hbm2java
 */
@Entity
@Table(name = "R_Contratista_Obra", catalog = "PGF")
public class RContratistaObra implements java.io.Serializable {

	private RContratistaObraId id;

	public RContratistaObra() {
	}

	public RContratistaObra(RContratistaObraId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idContratista", column = @Column(name = "idContratista", nullable = false) ),
			@AttributeOverride(name = "idActividad", column = @Column(name = "idActividad", nullable = false) ),
			@AttributeOverride(name = "idObra", column = @Column(name = "idObra", nullable = false) ) })
	public RContratistaObraId getId() {
		return this.id;
	}

	public void setId(RContratistaObraId id) {
		this.id = id;
	}

}
