package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RContratistaObraId generated by hbm2java
 */
@Embeddable
public class RContratistaObraId implements java.io.Serializable {

	private int idContratista;
	private int idActividad;
	private int idObra;

	public RContratistaObraId() {
	}

	public RContratistaObraId(int idContratista, int idActividad, int idObra) {
		this.idContratista = idContratista;
		this.idActividad = idActividad;
		this.idObra = idObra;
	}

	@Column(name = "idContratista", nullable = false)
	public int getIdContratista() {
		return this.idContratista;
	}

	public void setIdContratista(int idContratista) {
		this.idContratista = idContratista;
	}

	@Column(name = "idActividad", nullable = false)
	public int getIdActividad() {
		return this.idActividad;
	}

	public void setIdActividad(int idActividad) {
		this.idActividad = idActividad;
	}

	@Column(name = "idObra", nullable = false)
	public int getIdObra() {
		return this.idObra;
	}

	public void setIdObra(int idObra) {
		this.idObra = idObra;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RContratistaObraId))
			return false;
		RContratistaObraId castOther = (RContratistaObraId) other;

		return (this.getIdContratista() == castOther.getIdContratista())
				&& (this.getIdActividad() == castOther.getIdActividad()) && (this.getIdObra() == castOther.getIdObra());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdContratista();
		result = 37 * result + this.getIdActividad();
		result = 37 * result + this.getIdObra();
		return result;
	}

}
