package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * RRubrosRol generated by hbm2java
 */
@Entity
@Table(name = "R_Rubros_Rol", catalog = "PGF")
public class RRubrosRol implements java.io.Serializable {

	private RRubrosRolId id;

	public RRubrosRol() {
	}

	public RRubrosRol(RRubrosRolId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "de", column = @Column(name = "De", nullable = false) ),
			@AttributeOverride(name = "a", column = @Column(name = "A", nullable = false) ),
			@AttributeOverride(name = "rubro", column = @Column(name = "Rubro", nullable = false) ) })
	public RRubrosRolId getId() {
		return this.id;
	}

	public void setId(RRubrosRolId id) {
		this.id = id;
	}

}
