package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RRubrosRolId generated by hbm2java
 */
@Embeddable
public class RRubrosRolId implements java.io.Serializable {

	private int de;
	private int a;
	private int rubro;

	public RRubrosRolId() {
	}

	public RRubrosRolId(int de, int a, int rubro) {
		this.de = de;
		this.a = a;
		this.rubro = rubro;
	}

	@Column(name = "De", nullable = false)
	public int getDe() {
		return this.de;
	}

	public void setDe(int de) {
		this.de = de;
	}

	@Column(name = "A", nullable = false)
	public int getA() {
		return this.a;
	}

	public void setA(int a) {
		this.a = a;
	}

	@Column(name = "Rubro", nullable = false)
	public int getRubro() {
		return this.rubro;
	}

	public void setRubro(int rubro) {
		this.rubro = rubro;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RRubrosRolId))
			return false;
		RRubrosRolId castOther = (RRubrosRolId) other;

		return (this.getDe() == castOther.getDe()) && (this.getA() == castOther.getA())
				&& (this.getRubro() == castOther.getRubro());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDe();
		result = 37 * result + this.getA();
		result = 37 * result + this.getRubro();
		return result;
	}

}
