package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RUsuarioActividadId generated by hbm2java
 */
@Embeddable
public class RUsuarioActividadId implements java.io.Serializable {

	private int idContratista;
	private int idActividad;

	public RUsuarioActividadId() {
	}

	public RUsuarioActividadId(int idContratista, int idActividad) {
		this.idContratista = idContratista;
		this.idActividad = idActividad;
	}

	@Column(name = "idContratista", nullable = false)
	public int getIdContratista() {
		return this.idContratista;
	}

	public void setIdContratista(int idContratista) {
		this.idContratista = idContratista;
	}

	@Column(name = "idActividad", nullable = false)
	public int getIdActividad() {
		return this.idActividad;
	}

	public void setIdActividad(int idActividad) {
		this.idActividad = idActividad;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RUsuarioActividadId))
			return false;
		RUsuarioActividadId castOther = (RUsuarioActividadId) other;

		return (this.getIdContratista() == castOther.getIdContratista())
				&& (this.getIdActividad() == castOther.getIdActividad());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdContratista();
		result = 37 * result + this.getIdActividad();
		return result;
	}

}
