package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * RUsuarioActividad generated by hbm2java
 */
@Entity
@Table(name = "R_Usuario_Actividad", catalog = "PGF")
public class RUsuarioActividad implements java.io.Serializable {

	private RUsuarioActividadId id;

	public RUsuarioActividad() {
	}

	public RUsuarioActividad(RUsuarioActividadId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idContratista", column = @Column(name = "idContratista", nullable = false) ),
			@AttributeOverride(name = "idActividad", column = @Column(name = "idActividad", nullable = false) ) })
	public RUsuarioActividadId getId() {
		return this.id;
	}

	public void setId(RUsuarioActividadId id) {
		this.id = id;
	}

}
