package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SolicitudPago generated by hbm2java
 */
@Entity
@Table(name = "Solicitud_Pago", catalog = "PGF")
public class SolicitudPago implements java.io.Serializable {

	private int idSolicitudPago;
	private String descripcion;
	private int CStastusSolicitudPagoIdCStastusSolicitudPago;
	private int RContratistaObraContratistaIdContratista;
	private int RContratistaObraObraIdObra;

	public SolicitudPago() {
	}

	public SolicitudPago(int idSolicitudPago, int CStastusSolicitudPagoIdCStastusSolicitudPago,
			int RContratistaObraContratistaIdContratista, int RContratistaObraObraIdObra) {
		this.idSolicitudPago = idSolicitudPago;
		this.CStastusSolicitudPagoIdCStastusSolicitudPago = CStastusSolicitudPagoIdCStastusSolicitudPago;
		this.RContratistaObraContratistaIdContratista = RContratistaObraContratistaIdContratista;
		this.RContratistaObraObraIdObra = RContratistaObraObraIdObra;
	}

	public SolicitudPago(int idSolicitudPago, String descripcion, int CStastusSolicitudPagoIdCStastusSolicitudPago,
			int RContratistaObraContratistaIdContratista, int RContratistaObraObraIdObra) {
		this.idSolicitudPago = idSolicitudPago;
		this.descripcion = descripcion;
		this.CStastusSolicitudPagoIdCStastusSolicitudPago = CStastusSolicitudPagoIdCStastusSolicitudPago;
		this.RContratistaObraContratistaIdContratista = RContratistaObraContratistaIdContratista;
		this.RContratistaObraObraIdObra = RContratistaObraObraIdObra;
	}

	@Id

	@Column(name = "idSolicitud_Pago", unique = true, nullable = false)
	public int getIdSolicitudPago() {
		return this.idSolicitudPago;
	}

	public void setIdSolicitudPago(int idSolicitudPago) {
		this.idSolicitudPago = idSolicitudPago;
	}

	@Column(name = "Descripcion", length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "C_Stastus_Solicitud_Pago_idC_Stastus_Solicitud_Pago", nullable = false)
	public int getCStastusSolicitudPagoIdCStastusSolicitudPago() {
		return this.CStastusSolicitudPagoIdCStastusSolicitudPago;
	}

	public void setCStastusSolicitudPagoIdCStastusSolicitudPago(int CStastusSolicitudPagoIdCStastusSolicitudPago) {
		this.CStastusSolicitudPagoIdCStastusSolicitudPago = CStastusSolicitudPagoIdCStastusSolicitudPago;
	}

	@Column(name = "R_Contratista_Obra_Contratista_idContratista", nullable = false)
	public int getRContratistaObraContratistaIdContratista() {
		return this.RContratistaObraContratistaIdContratista;
	}

	public void setRContratistaObraContratistaIdContratista(int RContratistaObraContratistaIdContratista) {
		this.RContratistaObraContratistaIdContratista = RContratistaObraContratistaIdContratista;
	}

	@Column(name = "R_Contratista_Obra_Obra_idObra", nullable = false)
	public int getRContratistaObraObraIdObra() {
		return this.RContratistaObraObraIdObra;
	}

	public void setRContratistaObraObraIdObra(int RContratistaObraObraIdObra) {
		this.RContratistaObraObraIdObra = RContratistaObraObraIdObra;
	}

}
