package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SolicitudPagoChange generated by hbm2java
 */
@Entity
@Table(name = "Solicitud_Pago_Change", catalog = "PGF")
public class SolicitudPagoChange implements java.io.Serializable {

	private SolicitudPagoChangeId id;

	public SolicitudPagoChange() {
	}

	public SolicitudPagoChange(SolicitudPagoChangeId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idSolicitudPagoChange", column = @Column(name = "idSolicitud_Pago_Change", nullable = false) ),
			@AttributeOverride(name = "deStatus", column = @Column(name = "De_Status", nullable = false) ),
			@AttributeOverride(name = "AStastus", column = @Column(name = "A_Stastus", nullable = false) ),
			@AttributeOverride(name = "usuarioIdUsuario", column = @Column(name = "Usuario_idUsuario", nullable = false) ) })
	public SolicitudPagoChangeId getId() {
		return this.id;
	}

	public void setId(SolicitudPagoChangeId id) {
		this.id = id;
	}

}
