package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TelefonoId generated by hbm2java
 */
@Embeddable
public class TelefonoId implements java.io.Serializable {

	private int idTelefono;
	private int usuarioIdUsuario;

	public TelefonoId() {
	}

	public TelefonoId(int idTelefono, int usuarioIdUsuario) {
		this.idTelefono = idTelefono;
		this.usuarioIdUsuario = usuarioIdUsuario;
	}

	@Column(name = "idTelefono", nullable = false)
	public int getIdTelefono() {
		return this.idTelefono;
	}

	public void setIdTelefono(int idTelefono) {
		this.idTelefono = idTelefono;
	}

	@Column(name = "Usuario_idUsuario", nullable = false)
	public int getUsuarioIdUsuario() {
		return this.usuarioIdUsuario;
	}

	public void setUsuarioIdUsuario(int usuarioIdUsuario) {
		this.usuarioIdUsuario = usuarioIdUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TelefonoId))
			return false;
		TelefonoId castOther = (TelefonoId) other;

		return (this.getIdTelefono() == castOther.getIdTelefono())
				&& (this.getUsuarioIdUsuario() == castOther.getUsuarioIdUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdTelefono();
		result = 37 * result + this.getUsuarioIdUsuario();
		return result;
	}

}
