package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UnidadNegocio generated by hbm2java
 */
@Entity
@Table(name = "Unidad_Negocio", catalog = "PGF")
public class UnidadNegocio implements java.io.Serializable {

	private int idUnidadNegocio;
	private String nombre;

	public UnidadNegocio() {
	}

	public UnidadNegocio(int idUnidadNegocio) {
		this.idUnidadNegocio = idUnidadNegocio;
	}

	public UnidadNegocio(int idUnidadNegocio, String nombre) {
		this.idUnidadNegocio = idUnidadNegocio;
		this.nombre = nombre;
	}

	@Id

	@Column(name = "idUnidad_Negocio", unique = true, nullable = false)
	public int getIdUnidadNegocio() {
		return this.idUnidadNegocio;
	}

	public void setIdUnidadNegocio(int idUnidadNegocio) {
		this.idUnidadNegocio = idUnidadNegocio;
	}

	@Column(name = "Nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
