package ixpan.pgf.model;
// Generated Aug 26, 2015 10:06:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "Usuario", catalog = "PGF")
public class Usuario implements java.io.Serializable {

	private Integer idUsuario;
	private String userName;
	private String contrasena;
	private int idRolUsuario;
	private String nombre;
	private String apellido;
	private String email;
	private String ife;
	private String status;
	private String actaHacienda;
	private String actaConstitutiva;
	private String infraestructura;
	private String datosFiscales;
	private String capacidadGeneral;
	private String capacidadFinanciera;
	private Integer calificacionGlobal;
	private Integer direccionFiscal;
	private Integer direccionPersonal;

	public Usuario() {
	}

	public Usuario(String contrasena, int idRolUsuario, String nombre, String apellido, String email, String status) {
		this.contrasena = contrasena;
		this.idRolUsuario = idRolUsuario;
		this.nombre = nombre;
		this.apellido = apellido;
		this.email = email;
		this.status = status;
	}

	public Usuario(String userName, String contrasena, int idRolUsuario, String nombre, String apellido, String email,
			String ife, String status, String actaHacienda, String actaConstitutiva, String infraestructura,
			String datosFiscales, String capacidadGeneral, String capacidadFinanciera, Integer calificacionGlobal,
			Integer direccionFiscal, Integer direccionPersonal) {
		this.userName = userName;
		this.contrasena = contrasena;
		this.idRolUsuario = idRolUsuario;
		this.nombre = nombre;
		this.apellido = apellido;
		this.email = email;
		this.ife = ife;
		this.status = status;
		this.actaHacienda = actaHacienda;
		this.actaConstitutiva = actaConstitutiva;
		this.infraestructura = infraestructura;
		this.datosFiscales = datosFiscales;
		this.capacidadGeneral = capacidadGeneral;
		this.capacidadFinanciera = capacidadFinanciera;
		this.calificacionGlobal = calificacionGlobal;
		this.direccionFiscal = direccionFiscal;
		this.direccionPersonal = direccionPersonal;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idUsuario", unique = true, nullable = false)
	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "userName", length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "contrasena", nullable = false, length = 45)
	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	@Column(name = "idRol_Usuario", nullable = false)
	public int getIdRolUsuario() {
		return this.idRolUsuario;
	}

	public void setIdRolUsuario(int idRolUsuario) {
		this.idRolUsuario = idRolUsuario;
	}

	@Column(name = "Nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Apellido", nullable = false, length = 45)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Column(name = "Email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "IFE", length = 45)
	public String getIfe() {
		return this.ife;
	}

	public void setIfe(String ife) {
		this.ife = ife;
	}

	@Column(name = "Status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "actaHacienda", length = 45)
	public String getActaHacienda() {
		return this.actaHacienda;
	}

	public void setActaHacienda(String actaHacienda) {
		this.actaHacienda = actaHacienda;
	}

	@Column(name = "actaConstitutiva", length = 45)
	public String getActaConstitutiva() {
		return this.actaConstitutiva;
	}

	public void setActaConstitutiva(String actaConstitutiva) {
		this.actaConstitutiva = actaConstitutiva;
	}

	@Column(name = "infraestructura", length = 45)
	public String getInfraestructura() {
		return this.infraestructura;
	}

	public void setInfraestructura(String infraestructura) {
		this.infraestructura = infraestructura;
	}

	@Column(name = "datosFiscales", length = 45)
	public String getDatosFiscales() {
		return this.datosFiscales;
	}

	public void setDatosFiscales(String datosFiscales) {
		this.datosFiscales = datosFiscales;
	}

	@Column(name = "capacidadGeneral", length = 45)
	public String getCapacidadGeneral() {
		return this.capacidadGeneral;
	}

	public void setCapacidadGeneral(String capacidadGeneral) {
		this.capacidadGeneral = capacidadGeneral;
	}

	@Column(name = "capacidadFinanciera", length = 45)
	public String getCapacidadFinanciera() {
		return this.capacidadFinanciera;
	}

	public void setCapacidadFinanciera(String capacidadFinanciera) {
		this.capacidadFinanciera = capacidadFinanciera;
	}

	@Column(name = "calificacionGlobal")
	public Integer getCalificacionGlobal() {
		return this.calificacionGlobal;
	}

	public void setCalificacionGlobal(Integer calificacionGlobal) {
		this.calificacionGlobal = calificacionGlobal;
	}

	@Column(name = "DireccionFiscal")
	public Integer getDireccionFiscal() {
		return this.direccionFiscal;
	}

	public void setDireccionFiscal(Integer direccionFiscal) {
		this.direccionFiscal = direccionFiscal;
	}

	@Column(name = "DireccionPersonal")
	public Integer getDireccionPersonal() {
		return this.direccionPersonal;
	}

	public void setDireccionPersonal(Integer direccionPersonal) {
		this.direccionPersonal = direccionPersonal;
	}

}
